function out = func_ReadFiles(subj, ses, task_name)

ffiles = dir(fullfile(subj.dir, ses, 'func'));
ffiles = ffiles(3:end);
sfiles = dir(fullfile(subj.dir, ses, 'anat'));
sfiles = sfiles(3:end);

fdata = ffiles(contains({ffiles.name}, 'msc') & ...
    contains({ffiles.name}, subj.name) & ...
    contains({ffiles.name}, ses) & ...
    contains({ffiles.name}, ['task-' task_name]) & ...
    contains({ffiles.name}, 'dir-AP') & ...
    contains({ffiles.name}, 'bold.nii'));

meanfdata = ffiles(contains({ffiles.name}, 'mean_') & ...
    contains({ffiles.name}, subj.name) & ...
    contains({ffiles.name}, ses) & ...
    contains({ffiles.name}, ['task-' task_name]) & ...
    contains({ffiles.name}, 'dir-AP') & ...
    contains({ffiles.name}, 'bold.nii'));

sdata = sfiles(contains({sfiles.name}, subj.name) & ...
    contains({sfiles.name}, ses) & ...
    contains({sfiles.name}, 'T1w.nii'));

out = {fullfile(fdata.folder, fdata.name), ...
       fullfile(meanfdata.folder, meanfdata.name), ...
       fullfile(sdata.folder, sdata.name)};